using UnityEngine.UIElements;

namespace MCV_Module.UI.AgentCanvas
{
    /// <summary>
    /// AgentCanvas UI Toolkit 样式系统 — 通过 C# 定义样式规则。
    ///
    /// 同时生成 .uss 文件供 Unity Editor 导入使用:
    ///   Assets/Resources/UI/AgentCanvas/AgentCanvasStyles.uss
    ///
    /// USS 注意事项（参考 ui-toolkit skill）:
    ///   - 使用 flex/none（无 block/inline）
    ///   - 颜色使用 #RRGGBBAA 格式（无 rgba()）
    ///   - 位置使用 px / % / auto（无 em/rem/calc）
    ///   - text-align 使用 -unity-text-align 属性
    /// </summary>
    public static class AgentCanvasStyles
    {
        /// <summary>将样式应用到指定 VisualElement。</summary>
        public static void ApplyRootStyles(VisualElement root)
        {
            if (root == null) return;

            root.style.backgroundColor = new StyleColor(new UnityEngine.Color(0.961f, 0.941f, 0.910f)); // #F5F0E8
            root.style.fontSize = 15;
            root.style.color = new StyleColor(new UnityEngine.Color(0.173f, 0.173f, 0.173f)); // #2C2C2C
        }

        /// <summary>生成 USS 文件内容（供 Editor 导入使用）。</summary>
        public static string GenerateUSS()
        {
            return @"/* AgentCanvas UI Toolkit Styles */
/* Generated by AgentCanvasStyles.cs — 注意 USS ≠ CSS */

/* ── 根容器 ── */
#agent-canvas-root {
    background-color: #EBEBF2;
    font-size: 14px;
    color: #262633;
    flex-grow: 1;
}

/* ── 通用元件 ── */
.agent-element {
    margin-bottom: 8px;
}

/* ── 标题 ── */
.agent-title {
    margin-bottom: 12px;
}
.agent-title-text {
    font-size: 24px;
    -unity-font-style: bold;
    color: #1A1A2E;
    -unity-text-align: middle-center;
}

/* ── 小标题+文字 ── */
.agent-subtitle-text {
    padding: 8px;
}
.agent-subtitle-title {
    font-size: 18px;
    -unity-font-style: bold;
    color: #2C3E50;
    margin-bottom: 4px;
}
.agent-subtitle-content {
    font-size: 14px;
    color: #34495E;
    white-space: normal;
}

/* ── 图片 ── */
.agent-image {
    padding: 4px;
}
.agent-image-element {
    flex-grow: 1;
    min-height: 120px;
}
.agent-image-caption {
    font-size: 12px;
    color: #7F8C8D;
    -unity-text-align: middle-center;
    margin-top: 4px;
}

/* ── 图文 ── */
.agent-image-text {
    padding: 8px;
}
.agent-image-text-image {
    min-height: 100px;
}
.agent-image-text-title {
    font-size: 16px;
    -unity-font-style: bold;
    margin-bottom: 4px;
}
.agent-image-text-body {
    font-size: 13px;
    color: #2C3E50;
    white-space: normal;
}

/* ── 选择题 ── */
.agent-choice {
    padding: 10px;
    background-color: #F8F9FA;
    border-color: #DEE2E6;
    border-width: 1px;
}
.agent-choice-question {
    font-size: 15px;
    -unity-font-style: bold;
    margin-bottom: 8px;
}
.agent-choice-options {
    margin-bottom: 8px;
}
.agent-choice-submit {
    background-color: #3498DB;
    color: white;
    border-radius: 4px;
    padding: 6px 16px;
    align-self: flex-start;
}
.agent-choice-correct {
    background-color: #D4EDDA;
}

/* ── 填空题 ── */
.agent-fill {
    padding: 10px;
    background-color: #F8F9FA;
    border-color: #DEE2E6;
    border-width: 1px;
}
.agent-fill-question {
    font-size: 15px;
    -unity-font-style: bold;
    margin-bottom: 8px;
}
.agent-fill-input {
    margin-bottom: 8px;
}
.agent-fill-submit {
    background-color: #3498DB;
    color: white;
    border-radius: 4px;
    padding: 6px 16px;
    align-self: flex-start;
}

/* ── 模型 ── */
.agent-model {
    padding: 8px;
    min-height: 200px;
}
.agent-model-label {
    font-size: 14px;
    -unity-font-style: bold;
    margin-bottom: 4px;
}
.agent-model-viewport {
    background-color: #E8E8EE;
    border-color: #CCC;
    border-width: 1px;
    flex-grow: 1;
}

/* ── 视频 ── */
.agent-video {
    padding: 8px;
    min-height: 180px;
}
.agent-video-label {
    font-size: 14px;
    -unity-font-style: bold;
    margin-bottom: 4px;
}
.agent-video-player {
    background-color: #1A1A2E;
    flex-grow: 1;
}

/* ── 按钮 ── */
.agent-button {
    padding: 4px;
}
.agent-button-element {
    background-color: #2ECC71;
    color: white;
    border-radius: 4px;
    padding: 8px 20px;
    font-size: 15px;
    align-self: flex-start;
}

/* ── 按钮列表 ── */
.agent-button-list {
    padding: 8px;
}
.agent-button-list-title {
    font-size: 15px;
    -unity-font-style: bold;
    margin-bottom: 6px;
}
.agent-button-list-item {
    background-color: #ECF0F1;
    color: #2C3E50;
    border-color: #BDC3C7;
    border-width: 1px;
    border-radius: 4px;
    padding: 8px 16px;
    margin-bottom: 4px;
    -unity-text-align: middle-center;
}

/* ── 反馈 ── */
.agent-feedback {
    margin-top: 8px;
    padding: 8px;
    border-radius: 4px;
}
.agent-result-correct {
    background-color: #D4EDDA;
    color: #155724;
    font-size: 13px;
    white-space: normal;
}
.agent-result-incorrect {
    background-color: #F8D7DA;
    color: #721C24;
    font-size: 13px;
    white-space: normal;
}

/* ── Markdown ── */
.agent-markdown {
    padding: 4px;
}
.agent-markdown-h1 {
    font-size: 22px;
    -unity-font-style: bold;
    margin-bottom: 8px;
    color: #1A1A2E;
}
.agent-markdown-h2 {
    font-size: 18px;
    -unity-font-style: bold;
    margin-bottom: 6px;
    color: #2C3E50;
}
.agent-markdown-h3 {
    font-size: 15px;
    -unity-font-style: bold;
    margin-bottom: 4px;
    color: #34495E;
}
.agent-markdown-paragraph {
    font-size: 13px;
    color: #2C3E50;
    white-space: normal;
    margin-bottom: 4px;
}
.agent-markdown-list-item {
    margin-bottom: 2px;
    padding-left: 8px;
}
.agent-markdown-bullet {
    font-size: 13px;
    color: #2C3E50;
    min-width: 16px;
}
.agent-markdown-text {
    font-size: 13px;
    color: #2C3E50;
    white-space: normal;
}
";
        }
    }
}
